//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apartments()
        {
            this.meters = new HashSet<meters>();
            this.residents = new HashSet<residents>();
        }
    
        public int id { get; set; }
        public Nullable<int> house_id { get; set; }
        public string number { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<int> ownership_type_id { get; set; }
    
        public virtual houses houses { get; set; }
        public virtual ownership_types ownership_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meters> meters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<residents> residents { get; set; }
    }
}
