//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdMod : DbContext
    {
        private static bdMod context;

        public bdMod()
            : base("name=bdMod")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<calculation_bases> calculation_bases { get; set; }
        public virtual DbSet<calculation_types> calculation_types { get; set; }
        public virtual DbSet<charges> charges { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<houses> houses { get; set; }
        public virtual DbSet<meter_types> meter_types { get; set; }
        public virtual DbSet<meters> meters { get; set; }
        public virtual DbSet<ownership_types> ownership_types { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<request_statuses> request_statuses { get; set; }
        public virtual DbSet<residents> residents { get; set; }
        public virtual DbSet<service_requests> service_requests { get; set; }
        public virtual DbSet<service_types> service_types { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<users> users { get; set; }

        public static bdMod GetContext(bool check)
        {
            if (context == null || check)
                context = new bdMod();
            return context;
        }
    }
}
