//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class charges
    {
        public int id { get; set; }
        public Nullable<int> resident_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<System.DateTime> period { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> consumption { get; set; }
        public Nullable<int> calculation_type_id { get; set; }
    
        public virtual calculation_types calculation_types { get; set; }
        public virtual residents residents { get; set; }
        public virtual services services { get; set; }
    }
}
