//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.service_requests = new HashSet<service_requests>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string name { get; set; }
        public string surname { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string department { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_requests> service_requests { get; set; }
    }
}
