//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class meters
    {
        public int id { get; set; }
        public Nullable<int> apartment_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> meter_type_id { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> installation_date { get; set; }
        public Nullable<decimal> current_reading { get; set; }
        public Nullable<System.DateTime> last_reading_date { get; set; }
        public Nullable<decimal> last_reading_value { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual apartments apartments { get; set; }
        public virtual meter_types meter_types { get; set; }
        public virtual services services { get; set; }
    }
}
