//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public services()
        {
            this.charges = new HashSet<charges>();
            this.meters = new HashSet<meters>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type_id { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> tariff { get; set; }
        public Nullable<int> calculation_base_id { get; set; }
    
        public virtual calculation_bases calculation_bases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<charges> charges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meters> meters { get; set; }
        public virtual service_types service_types { get; set; }
    }
}
