//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_requests
    {
        public int id { get; set; }
        public Nullable<int> resident_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> assigned_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual request_statuses request_statuses { get; set; }
        public virtual residents residents { get; set; }
    }
}
