//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3_pogram_mod.bd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users(string username, string email, string password, int role_id, bool isActive)
        {
            this.username = username;
            this.password = password;
            this.email = email;
            this.role_id = role_id;
            this.is_active = isActive;

            this.employees = new HashSet<employees>();
            this.residents = new HashSet<residents>();
        }

        public users()
        {
            this.employees = new HashSet<employees>();
            this.residents = new HashSet<residents>();
        }

        public int id { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 5, ErrorMessage ="Имя должно быть мимнимум 5 и макс 20")]
        public string username { get; set; }

        [Required]
        [MinLength(5, ErrorMessage = "Пароль должнен содержать минимум 5 символов")]
        public string password { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 5)]
        [EmailAddress(ErrorMessage = "Некорректный адрес электронной почты")]
        public string email { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "ID роли должен быть больше 0")]
        public int role_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employees> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<residents> residents { get; set; }
        public virtual user_roles user_roles { get; set; }
    }
}
